name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: speak-mate-mvp
  REGION: europe-west1
  REPO_NAME: saynestlab-website-image
  IMAGE_NAME: saynest-lab-frontend-website
  SERVICE_NAME: saynestlab-landing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag image for Artifact Registry
        run: |
          docker tag $IMAGE_NAME $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME

      - name: Push image to Artifact Registry
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --min-instances=0
